### ISSUE TITLE
root:B3 site is not responding

### ISSUE THREAD

**Issue by TeodoroRodrigo** [pedroprates/b3bovespa#1]
Olá pedroprates, 

Muito boa a implementação, parabéns.
Aqui ficou dando esse erro a cada tentativa, rodei pelo firefox.
![image](https://user-images.githubusercontent.com/26728400/97903261-822a4f00-1d1d-11eb-8fe3-bb8ee8c83151.png)

**Comment by pedroprates** [comment]
Olá @r-teodoro! 

O site da B3 as vezes demora para carregar, e o `B3 site is not responding` é apenas para informar que o tempo de espera superou o timeout setado. Vou fazer uma modificação para transformar em um warning, e tentar verificar se podemos ter algum motivo para a demora a resposta.

Obrigado!
